# Generated by Django 3.2.4 on 2021-06-23 22:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leadorganisations', models.CharField(max_length=500)),
                ('projectname', models.CharField(max_length=500)),
                ('province', models.CharField(choices=[('a', 'Select'), ('b', ' Eastern Cape'), ('c', 'Free State'), ('d', 'Gauteng'), ('e', 'KwaZulu-Natal'), ('f', 'Limpopo'), ('g', 'Mpumalanga'), ('h', 'Northern Cape'), ('i', 'North West'), ('j', 'Western Cape'), ('k', 'All nationals'), ('l', 'International')], default='Select', max_length=500)),
                ('city', models.CharField(blank=True, max_length=500)),
                ('projectlogo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('maintheme', models.CharField(max_length=500)),
                ('topic', models.CharField(max_length=500)),
                ('website', models.CharField(blank=True, max_length=500)),
                ('linkedin', models.CharField(blank=True, max_length=500)),
                ('startdate', models.DateTimeField(blank=True, null=True)),
                ('enddate', models.DateTimeField(blank=True, null=True)),
                ('projectsummary', models.TextField()),
                ('whatwedo', models.TextField()),
                ('howwedo', models.TextField()),
                ('achieved', models.TextField()),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_time'],
            },
        ),
    ]
