# Generated by Django 3.2.4 on 2021-06-23 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='bachieved',
            field=models.TextField(default=''),
        ),
    ]
