# Generated by Django 3.2.4 on 2021-06-23 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_bachieved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='bachieved',
        ),
    ]
