# Generated by Django 3.2.4 on 2021-06-23 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_projectparticipant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectparticipant',
            old_name='discussion',
            new_name='project',
        ),
    ]
