# Generated by Django 3.2.4 on 2021-06-28 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_alter_project_province'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='linkedin',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='project',
            name='website',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
