# Generated by Django 3.2.4 on 2021-06-29 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_auto_20210629_0155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='province',
            field=models.IntegerField(blank='false', choices=[(1, 'Select'), (2, ' Eastern Cape'), (3, 'Free State'), (4, 'Gauteng'), (5, 'KwaZulu-Natal'), (6, 'Limpopo'), (7, 'Mpumalanga'), (8, 'Northern Cape'), (9, 'North West'), (10, 'Western Cape'), (11, 'All nationals'), (12, 'International')], default=1),
        ),
    ]
