# Generated by Django 3.2.4 on 2021-07-01 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_alter_project_province'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='projectlogo',
        ),
    ]
