# Generated by Django 3.2.4 on 2021-07-15 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_project_projectlogo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='leadorganisations',
            field=models.CharField(default='', max_length=500, verbose_name='Lead Organisation'),
        ),
        migrations.AlterField(
            model_name='project',
            name='projectname',
            field=models.CharField(max_length=500, verbose_name='Project Name'),
        ),
    ]
