# Generated by Django 3.2.4 on 2021-07-18 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_alter_project_projectlogo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='projectlogo',
            field=models.ImageField(blank=True, upload_to='images/', verbose_name='Project Logo'),
        ),
    ]
