# Generated by Django 3.2.4 on 2021-07-19 11:32

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_alter_project_projectsummary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='province',
        ),
        migrations.AddField(
            model_name='project',
            name='publisher',
            field=models.CharField(default='', max_length=500, verbose_name='Publisher'),
        ),
        migrations.AlterField(
            model_name='project',
            name='projectsummary',
            field=ckeditor.fields.RichTextField(verbose_name='Research Summary'),
        ),
    ]
