# Generated by Django 3.2.4 on 2021-08-07 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0002_organisation_province'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='mission',
            field=models.TextField(verbose_name='Mission'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='projectlogo',
            field=models.ImageField(blank=True, upload_to='documents/', verbose_name='Research Paper'),
        ),
    ]
