# Generated by Django 3.2.4 on 2021-06-29 03:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resourcetitle', models.CharField(max_length=500)),
                ('resourcedescription', models.CharField(max_length=500)),
                ('publisher', models.CharField(max_length=500)),
                ('publicationdate', models.DateTimeField(blank=True, null=True)),
                ('files', models.CharField(blank=True, max_length=500)),
                ('websitelink', models.CharField(blank=True, max_length=500)),
                ('videolink', models.CharField(blank=True, max_length=500)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_time'],
            },
        ),
        migrations.CreateModel(
            name='ReportParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.report')),
            ],
        ),
    ]
