# Generated by Django 3.2.4 on 2021-07-19 11:32

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='files',
        ),
        migrations.RemoveField(
            model_name='report',
            name='publicationdate',
        ),
        migrations.RemoveField(
            model_name='report',
            name='publisher',
        ),
        migrations.RemoveField(
            model_name='report',
            name='resourcedescription',
        ),
        migrations.RemoveField(
            model_name='report',
            name='videolink',
        ),
        migrations.RemoveField(
            model_name='report',
            name='websitelink',
        ),
        migrations.AddField(
            model_name='report',
            name='Description',
            field=ckeditor.fields.RichTextField(default='', verbose_name='Description of the Issue'),
        ),
        migrations.AddField(
            model_name='report',
            name='Priority',
            field=models.IntegerField(blank='false', choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')], default=1, verbose_name='Priority'),
        ),
        migrations.AddField(
            model_name='report',
            name='Reproducibility',
            field=models.IntegerField(blank='false', choices=[(1, '10%'), (2, '25%'), (3, '50%'), (4, '75%'), (5, '100%')], default=1, verbose_name='Reproducibility'),
        ),
        migrations.AddField(
            model_name='report',
            name='media',
            field=models.ImageField(blank=True, upload_to='images/', verbose_name='Provide Picture/Video'),
        ),
        migrations.AddField(
            model_name='report',
            name='severity',
            field=models.IntegerField(blank='false', choices=[(1, 'Select'), (2, 'Critical'), (3, 'Major'), (4, 'Moderate'), (5, 'Minor'), (6, 'Cosmetic')], default=1, verbose_name='Severity'),
        ),
    ]
