# Generated by Django 3.2.4 on 2021-08-01 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_board_post_topic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='created_by',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='message',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='created_dt',
            new_name='created_on',
        ),
        migrations.RemoveField(
            model_name='post',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='post',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='post',
            name='updated_dt',
        ),
    ]
