# Generated by Django 3.2.4 on 2021-08-10 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0009_auto_20210810_2259'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image',
            new_name='imageuser',
        ),
    ]
