# Generated by Django 3.2.4 on 2021-08-14 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_auto_20210808_0053'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='email',
            field=models.EmailField(default='', max_length=254, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='event',
            name='logo',
            field=models.ImageField(blank=True, upload_to='documents/', verbose_name='Research Paper'),
        ),
        migrations.AddField(
            model_name='event',
            name='website',
            field=models.URLField(blank=True, verbose_name='Website'),
        ),
    ]
