# Generated by Django 3.2.4 on 2021-06-24 14:59

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Homepages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_1', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('logo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('background', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('maincontent', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('image_1', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('image_2', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
            ],
        ),
    ]
