# Generated by Django 3.2.4 on 2021-07-15 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research',
            name='city',
            field=models.CharField(blank=True, max_length=500, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='research',
            name='collab',
            field=models.TextField(blank=True, verbose_name='Collaboration'),
        ),
        migrations.AlterField(
            model_name='research',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='research',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='research',
            name='enddate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='research',
            name='funding',
            field=models.TextField(blank=True, verbose_name='Funding'),
        ),
        migrations.AlterField(
            model_name='research',
            name='leadresearcher',
            field=models.CharField(max_length=500, verbose_name='Lead Researcher'),
        ),
        migrations.AlterField(
            model_name='research',
            name='maintheme',
            field=models.TextField(verbose_name='Main Theme'),
        ),
        migrations.AlterField(
            model_name='research',
            name='publisher',
            field=models.CharField(blank='false', default=1, max_length=500, verbose_name='Publisher'),
        ),
        migrations.AlterField(
            model_name='research',
            name='startdate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='research',
            name='title',
            field=models.CharField(default='', max_length=500, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='research',
            name='topic',
            field=models.TextField(verbose_name='Topic'),
        ),
        migrations.AlterField(
            model_name='research',
            name='website',
            field=models.URLField(blank=True, verbose_name='Website'),
        ),
    ]
