# Generated by Django 3.2.4 on 2021-07-18 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0002_auto_20210716_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research',
            name='publisher',
            field=models.CharField(blank='false', default='', max_length=500, verbose_name='Publisher'),
        ),
    ]
