# Generated by Django 3.2.4 on 2021-08-04 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0005_headline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='research',
            name='maintheme',
        ),
    ]
