# Generated by Django 3.2.4 on 2021-08-04 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0006_remove_research_maintheme'),
    ]

    operations = [
        migrations.AddField(
            model_name='research',
            name='researchfile',
            field=models.FileField(blank=True, upload_to='documents/', verbose_name='Research Paper'),
        ),
    ]
