# Generated by Django 3.2.4 on 2021-08-04 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0007_research_researchfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='research',
            name='topic',
        ),
        migrations.AlterField(
            model_name='research',
            name='description',
            field=models.TextField(default='', verbose_name='Research Summary'),
        ),
        migrations.AlterField(
            model_name='research',
            name='publisher',
            field=models.CharField(max_length=500, verbose_name='Publisher'),
        ),
    ]
